name: Simple Nix Flakes powered php ci.

on: [push, pull_request]

jobs:
  ci:

    runs-on: ubuntu-latest

    strategy:
      matrix:
          php: [php73, php74, php80]

    steps:
    - uses: actions/checkout@v2
      with:
        # Nix Flakes doesn't work on shallow clones
        fetch-depth: 0

    - uses: cachix/install-nix-action@v18

    - name: Cache Composer dependencies
      uses: actions/cache@v2
      with:
        path: /home/runner/.cache/composer
        key: ${{ runner.os }}-composer-${{ matrix.php }}-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-composer-

    - run: |
        rm -fr vendor
        nix shell .github#env-${{ matrix.php }} --command composer ci-prepare
        nix shell .github#env-${{ matrix.php }} --command composer ci
